
#include<iostream>
using namespace std;
int main(){

    cout<<"\n\tTic Tac Toe Game"<<endl;
    cout<<"\t\tPlayer1 [X]"<<endl;
    cout<<"\t\tPlayer2 [O]"<<endl<<endl;
    cout<<"\t\t\t        |        |        "<<endl;
    cout<<"\t\t\t    1   |    2   |   3    "<<endl;
    cout<<"\t\t\t________|________|________"<<endl;
    cout<<"\t\t\t        |        |        "<<endl;
    cout<<"\t\t\t    4   |   5    |   6    "<<endl;
    cout<<"\t\t\t________|________|________"<<endl;
    cout<<"\t\t\t        |        |        "<<endl;
    cout<<"\t\t\t    7   |    8   |   9    "<<endl;
    cout<<"\t\t\t        |        |        "<<endl;

    cout<<"\n\t\tPlayer1 [X] turn:";
    
    
    

    return 0;
}